version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongodb
    networks:
      - bayeta-net
    volumes:
      - mongo_data:/data/db

  bayeta:
    build: .
    container_name: bayeta
    depends_on:
      - mongo
    networks:
      - bayeta-net
    ports:
      - "5000:5000"
      

volumes:
  mongo_data:
  
networks:
  bayeta-net:
