version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongodb
    networks:
      - bayeta-net

  bayeta:
    build: .
    container_name: bayeta
    depends_on:
      - mongo
    networks:
      - bayeta-net
    ports:
      - "5000:5000"
      
networks:
  bayeta-net:
